// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rentier.Infrastructure.Persistence;

#nullable disable

namespace Rentier.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407134151_0009_FilingPaymentReference")]
    partial class _0009_FilingPaymentReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Rentier.Domain.Entities.Filing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FilingDeadline")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossIncomeRsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossTaxPayableRsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IncomeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayingEntity")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxPayableRsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TaxPeriod")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxpayerProfileId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WhtPaidRsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("TaxpayerProfileId");

                    b.ToTable("Filings", (string)null);
                });

            modelBuilder.Entity("Rentier.Domain.Entities.HolidayYearRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HolidayYearRange", (string)null);
                });

            modelBuilder.Entity("Rentier.Domain.Entities.Importer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentRegex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromFilter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<Guid?>("MailboxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentNotes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("ReportType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectFilter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<Guid?>("TaxpayerProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.HasIndex("TaxpayerProfileId");

                    b.ToTable("Importers", (string)null);
                });

            modelBuilder.Entity("Rentier.Domain.Entities.Mailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InitialSyncDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mailboxes", (string)null);
                });

            modelBuilder.Entity("Rentier.Domain.Entities.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year");

                    b.ToTable("PublicHolidays", (string)null);
                });

            modelBuilder.Entity("Rentier.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AttachmentContent")
                        .HasColumnType("BLOB");

                    b.Property<DateOnly>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImporterId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MailboxMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ImporterId");

                    b.HasIndex("ImporterId", "ReportName")
                        .IsUnique();

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Rentier.Domain.Entities.TaxpayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpstinaCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Jmbg")
                        .IsUnique();

                    b.ToTable("TaxpayerProfiles", (string)null);
                });

            modelBuilder.Entity("Rentier.Domain.ValueObjects.ExchangeRate", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateToRsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Date", "Currency");

                    b.ToTable("ExchangeRateCache", (string)null);
                });

            modelBuilder.Entity("Rentier.Domain.Entities.Filing", b =>
                {
                    b.HasOne("Rentier.Domain.Entities.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rentier.Domain.Entities.TaxpayerProfile", null)
                        .WithMany()
                        .HasForeignKey("TaxpayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rentier.Domain.Entities.Importer", b =>
                {
                    b.HasOne("Rentier.Domain.Entities.Mailbox", null)
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rentier.Domain.Entities.TaxpayerProfile", null)
                        .WithMany()
                        .HasForeignKey("TaxpayerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Rentier.Domain.Entities.Mailbox", b =>
                {
                    b.OwnsOne("Rentier.Domain.ValueObjects.MailboxCursor", "Cursor", b1 =>
                        {
                            b1.Property<Guid>("MailboxId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("LastSyncDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("Cursor_LastSyncDate");

                            b1.Property<long?>("LastUid")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Cursor_LastUid");

                            b1.HasKey("MailboxId");

                            b1.ToTable("Mailboxes");

                            b1.WithOwner()
                                .HasForeignKey("MailboxId");
                        });

                    b.Navigation("Cursor")
                        .IsRequired();
                });

            modelBuilder.Entity("Rentier.Domain.Entities.Report", b =>
                {
                    b.HasOne("Rentier.Domain.Entities.Importer", null)
                        .WithMany()
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
