<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rentier.Domain\Rentier.Domain.csproj" />
    <ProjectReference Include="..\Rentier.Application\Rentier.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ace4896.DBus.Services.Secrets" Version="1.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MailKit" Version="4.*" />
    <PackageReference Include="AngleSharp" Version="1.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.*" />
    <PackageReference Include="CsvHelper" Version="33.*" />
    <PackageReference Include="Velopack" Version="0.*" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Rentier.Infrastructure.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
