//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentier.Desktop.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
public static class Strings
{
    public static string AppTitle => "Rentier";
    public static string Nav_Filings => "Filings";
    public static string Nav_Reports => "Reports";
    public static string Nav_Settings => "Settings";
    public static string ComingSoon => "Coming soon";
}
