//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentier.Desktop.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
public static class Strings
{
    public static string AppTitle => "Rentier";
    public static string Nav_Filings => "Filings";
    public static string Nav_Reports => "Reports";
    public static string Nav_Settings => "Settings";
    public static string ComingSoon => "Coming soon";
    public static string Settings_Profile_TabHeader => "Profile";
    public static string Profile_Jmbg_Label => "JMBG (13 digits)";
    public static string Profile_FullName_Label => "Full Name";
    public static string Profile_Address_Label => "Address";
    public static string Profile_OpstinaCode_Label => "Opština Code";
    public static string Profile_PhoneNumber_Label => "Phone Number (optional)";
    public static string Profile_Email_Label => "Email (optional)";
    public static string Profile_Save_Button => "Save Profile";
    public static string Profile_Saved_Confirmation => "Profile saved successfully.";
    public static string Profile_JmbgValidation_Error => "JMBG must be exactly 13 digits.";
    public static string Profile_RequiredField_Error => "This field is required.";
    public static string Settings_Holidays_TabHeader => "Holidays";
    public static string Holidays_AddRow_Button => "Add";
    public static string Holidays_DeleteRow_Button => "Delete Selected";
    public static string Holidays_Save_Button => "Save";
    public static string Holidays_Import_Button => "Import from Web";
    public static string Holidays_Date_Column => "Date";
    public static string Holidays_Name_Column => "Name";
    public static string Holidays_StartYear_Label => "Start Year";
    public static string Holidays_EndYear_Label => "End Year";
    public static string Holidays_Saved_Confirmation => "Changes saved successfully.";
    public static string Holidays_ImportError_Prefix => "Import failed: ";
    public static string Holidays_ImportYear_Prompt => "Enter year to import:";
    public static string Holidays_InvalidDate_Error => "Invalid date format.";
    public static string Holidays_UnsavedChanges_Label => "Unsaved changes";
    public static string Settings_Mailboxes_TabHeader => "Mailboxes";
    public static string Mailboxes_Host_Label => "IMAP Host";
    public static string Mailboxes_Port_Label => "Port";
    public static string Mailboxes_Username_Label => "Username / Email";
    public static string Mailboxes_Password_Label => "Password";
    public static string Mailboxes_Password_Hint => "Leave blank to keep existing";
    public static string Mailboxes_InitialSyncDate_Label => "Sync From Date";
    public static string Mailboxes_AddNew_Button => "Add New";
    public static string Mailboxes_Save_Button => "Save";
    public static string Mailboxes_Delete_Button => "Delete";
    public static string Mailboxes_ErrorMessage_Label => "Error";
    public static string Mailboxes_SuccessMessage_Label => "Saved successfully";
    public static string Settings_Importers_TabHeader => "Importers";
    public static string Importers_DisplayName_Label => "Display Name";
    public static string Importers_ReportType_Label => "Report Type";
    public static string Importers_TaxpayerProfile_Label => "Taxpayer Profile";
    public static string Importers_Mailbox_Label => "Mailbox";
    public static string Importers_FromFilter_Label => "From Filter";
    public static string Importers_SubjectFilter_Label => "Subject Filter";
    public static string Importers_AttachmentRegex_Label => "Attachment Regex";
    public static string Importers_PaymentNotes_Label => "Payment Notes";
    public static string Importers_AddNew_Button => "Add New";
    public static string Importers_Save_Button => "Save";
    public static string Importers_Delete_Button => "Delete";
    public static string Importers_Saved_Confirmation => "Importer saved.";
    public static string Importers_NoProfile_Placeholder => "— No Profile —";
    public static string Importers_NoMailbox_Placeholder => "— No Mailbox —";
}
